import type { Metadata } from "next";

import { MarketingNav } from "@/components/marketing-nav";
import { SiteFooter } from "@/components/site-footer";

export const metadata: Metadata = {
  title: "Terms of Service — Ghost Palette",
  description: "The terms that govern your use of Ghost Palette.",
};

const LAST_UPDATED = "June 30, 2026";

export default function TermsPage() {
  return (
    <main className="gp-shell">
      <MarketingNav />
      <article className="gp-legal-page">
        <header className="gp-legal-page__head">
          <p className="gp-kicker">Legal</p>
          <h1>Terms of Service</h1>
          <p className="gp-legal-page__updated">Last updated: {LAST_UPDATED}</p>
        </header>

        <section className="gp-legal-section">
          <p>
            These Terms of Service (&ldquo;Terms&rdquo;) govern your access to and use
            of Ghost Palette (the &ldquo;Service,&rdquo; &ldquo;we,&rdquo;
            &ldquo;us,&rdquo; or &ldquo;our&rdquo;). By creating an account or using
            the Service, you agree to these Terms. If you do not agree, do not use
            the Service.
          </p>
        </section>

        <section className="gp-legal-section">
          <h2>1. The Service</h2>
          <p>
            Ghost Palette lets you generate images and videos from text prompts and
            reference images using third-party AI models, compare outputs across
            models, refine results, and save your generations to a personal Gallery.
            Generation is billed using a credit system: each generation deducts
            credits from your balance, and a failed generation is automatically
            refunded.
          </p>
        </section>

        <section className="gp-legal-section">
          <h2>2. Accounts</h2>
          <p>
            You must create an account to use generation features. You&rsquo;re
            responsible for safeguarding your account credentials and for all
            activity under your account. You must provide accurate information and
            promptly update it if it changes. You must be at least 18 years old, or
            the age of legal majority in your jurisdiction, to use the Service.
          </p>
        </section>

        <section className="gp-legal-section">
          <h2>3. Credits and Billing</h2>
          <p>
            Credits are purchased or granted (e.g., a starter allotment, a monthly
            subscription refresh) and consumed per generation, with cost varying by
            model. Paid plans are billed in advance through Stripe on a monthly or
            annual basis and renew automatically until cancelled. Credits expire or
            reset according to your plan&rsquo;s terms as described at checkout. We
            do not store your full payment card details — all payment processing is
            handled by Stripe.
          </p>
          <p>
            Except as required by law or expressly stated at the time of purchase,
            payments and unused credits are non-refundable. You can cancel a
            subscription at any time; cancellation takes effect at the end of the
            current billing period.
          </p>
        </section>

        <section className="gp-legal-section">
          <h2>4. Your Content and Generated Output</h2>
          <p>
            &ldquo;Your Content&rdquo; means the prompts, reference images, and other
            material you submit to the Service. You retain ownership of Your
            Content. By submitting it, you grant us a license to use, reproduce, and
            process it solely to operate the Service — including sending it to
            third-party AI model providers to generate output on your behalf, and
            storing prompts and generated media in your account so you can access
            them later.
          </p>
          <p>
            Subject to these Terms and to the underlying AI model providers&rsquo;
            own terms, you may use the images and videos the Service generates for
            you (&ldquo;Output&rdquo;). Because Output is generated by AI models, we
            cannot and do not guarantee that any Output is unique, that it does not
            resemble content generated for other users or pre-existing works, or
            that it is suitable for any particular purpose. You are responsible for
            ensuring your use of Output complies with applicable law and does not
            infringe third-party rights.
          </p>
        </section>

        <section className="gp-legal-section">
          <h2>5. Acceptable Use</h2>
          <p>You agree not to use the Service to generate, upload, or store content that:</p>
          <ul>
            <li>Is illegal, or depicts or facilitates illegal activity;</li>
            <li>
              Sexualizes minors in any way, or otherwise constitutes child sexual
              abuse material;
            </li>
            <li>
              Infringes another person&rsquo;s intellectual property, privacy, or
              publicity rights;
            </li>
            <li>
              Depicts real, identifiable people in a sexual, defamatory, or
              deliberately deceptive manner (including non-consensual intimate
              imagery or misleading &ldquo;deepfakes&rdquo;) without their consent;
            </li>
            <li>Is intended to harass, threaten, or incite violence against any person or group; or</li>
            <li>
              Attempts to circumvent the Service&rsquo;s credit system, rate limits,
              or security controls.
            </li>
          </ul>
          <p>
            We may remove content, suspend, or terminate accounts that violate this
            policy, with or without notice.
          </p>
        </section>

        <section className="gp-legal-section">
          <h2>6. Third-Party AI Models</h2>
          <p>
            Generation is performed by third-party AI model providers we integrate
            with. We do not control, and are not responsible for, the underlying
            models&rsquo; training data, behavior, or output quality. Output may be
            inaccurate, unexpected, or contain artifacts. Use your judgment before
            relying on or distributing any Output.
          </p>
        </section>

        <section className="gp-legal-section">
          <h2>7. Intellectual Property</h2>
          <p>
            The Service itself — its software, design, and branding (excluding Your
            Content and Output) — is owned by us or our licensors and protected by
            intellectual property law. These Terms don&rsquo;t grant you any rights
            to our trademarks or branding.
          </p>
        </section>

        <section className="gp-legal-section">
          <h2>8. Termination</h2>
          <p>
            You may stop using the Service and delete your account at any time. We
            may suspend or terminate your access if you violate these Terms, misuse
            the Service, or fail to pay amounts owed. Upon termination, your right
            to use the Service ends; provisions that by their nature should survive
            (e.g., Sections 4-7 and 9-11) will continue to apply.
          </p>
        </section>

        <section className="gp-legal-section">
          <h2>9. Disclaimers</h2>
          <p>
            THE SERVICE AND ALL OUTPUT ARE PROVIDED &ldquo;AS IS&rdquo; AND
            &ldquo;AS AVAILABLE,&rdquo; WITHOUT WARRANTIES OF ANY KIND, WHETHER
            EXPRESS, IMPLIED, OR STATUTORY, INCLUDING WARRANTIES OF
            MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
            NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE
            UNINTERRUPTED, ERROR-FREE, OR THAT GENERATED CONTENT WILL MEET YOUR
            EXPECTATIONS.
          </p>
        </section>

        <section className="gp-legal-section">
          <h2>10. Limitation of Liability</h2>
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, GHOST PALETTE AND ITS OFFICERS,
            EMPLOYEES, AND SERVICE PROVIDERS WILL NOT BE LIABLE FOR ANY INDIRECT,
            INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF
            PROFITS, DATA, OR GOODWILL, ARISING FROM YOUR USE OF THE SERVICE. OUR
            TOTAL LIABILITY FOR ANY CLAIM ARISING OUT OF THESE TERMS WILL NOT EXCEED
            THE AMOUNT YOU PAID US IN THE 12 MONTHS BEFORE THE CLAIM AROSE.
          </p>
        </section>

        <section className="gp-legal-section">
          <h2>11. Indemnification</h2>
          <p>
            You agree to defend, indemnify, and hold us harmless from any claims,
            damages, or expenses (including reasonable legal fees) arising from your
            use of the Service, Your Content, or your violation of these Terms.
          </p>
        </section>

        <section className="gp-legal-section">
          <h2>12. Governing Law</h2>
          <p>
            These Terms are governed by applicable law, without regard to
            conflict-of-laws principles. Any dispute arising from these Terms or
            the Service will be resolved in a court of competent jurisdiction.
          </p>
        </section>

        <section className="gp-legal-section">
          <h2>13. Changes to These Terms</h2>
          <p>
            We may update these Terms from time to time. If we make material
            changes, we&rsquo;ll update the &ldquo;Last updated&rdquo; date above and,
            where appropriate, notify you. Continued use of the Service after
            changes take effect constitutes acceptance of the revised Terms.
          </p>
        </section>

        <section className="gp-legal-section">
          <h2>14. Contact</h2>
          <p>
            Questions about these Terms? Email us at{" "}
            <a href="mailto:hello@ghostpalette.app">hello@ghostpalette.app</a>.
          </p>
        </section>
      </article>
      <SiteFooter />
    </main>
  );
}
